name: sea
channels:
    - ioos
    - pypi
dependencies:
    - Bottleneck=1.0.0
    - click=4.0
    - cytoolz=0.7.3
    - dask=0.6.0
    - dill=0.2.3
    - Flask=0.10.1
    - html5lib
    - ipython=3.2.0
    - itsdangerous=0.24
    - Jinja2=2.7.3
    - jsonschema
    - matplotlib=1.4.3
    - numexpr=2.4.3
    - numpy=1.9.2
    - pandas=0.16.2
    - partd=0.3.2
    - patsy=0.3.0
    - Pygments=2.0.2
    - pymongo
    - pyparsing=2.0.3
    - python=3.4
    - python-dateutil=2.4.2
    - pytz=2015.4
    - pyzmq=14.7.0
    - requests=2.7.0
    - scikit-learn=0.16.1
    - scipy=0.15.1
    - seaborn=0.6.0
    - six=1.9.0
    - snowballstemmer=1.2.0
    - statsmodels=0.6.1
    - pytables=3.2.0
    - toolz=0.7.2
    - tornado=4.2
    - Werkzeug=0.10.4
